### ISSUE TITLE
GHRC.IO IMAGES

### ISSUE THREAD

**Issue by doob187** [b4too/checker#1]
https://github.com/methatronc/checker/blob/6c37cec3738b2e6c637b20d314cde61a0fb82fcc/checker.sh#L3

Exclude images from GHRC.io repos 

Add
```sh
|  grep -v ghcr
```

**Comment by methatronc** [comment]
If you do that you won't be notified when linuxserver images will be updated, the 11th and 12th line sed is there to 'normalize' linuxserver images and allow notifications for them. For instance I was properly notified when the nextcloud image was updated the last few days. 
Unless there is something else I will close this issue ?

**Comment by doob187** [comment]
Some Docker creator don't store the images on Docker hub.
Only on GHRC.io 

So it will failed for this image

**Comment by methatronc** [comment]
Ok, I understand.
However `grep -v ghcr` will definitely remove the ability to know about linuxrserver images updates.
Could you share what a `docker ps --format "{{.Image}}"` outputs for the problematic image you're referring to ?

**Comment by doob187** [comment]
Some of the dockers are builded for my own use  case

```sh
ghcr.io/dockserver/docker-vnstat:latest
ghcr.io/linuxserver/sonarr:develop
ghcr.io/linuxserver/sonarr:develop
ghcr.io/dockserver/dockupdate:master
ghcr.io/dockserver/docker-uploader:dockserver
ghcr.io/dockserver/docker-mount:dockserver
ghcr.io/linuxserver/radarr:nightly
ghcr.io/linuxserver/radarr:nightly
ghcr.io/linuxserver/plex:latest
portainer/portainer-ce:latest
ghcr.io/linuxserver/sabnzbd:latest
ghcr.io/sct/overseerr:develop
ghcr.io/linuxserver/sabnzbd:latest
traefik:latest
authelia/authelia:latest
tiredofit/traefik-cloudflare-companion:latest
guillaumebriday/traefik-custom-error-pages
dockupdater/dockupdater
cloudb0x/autoscan:latest

```

**Comment by methatronc** [comment]
The latest commit excludes all kind of non-docker images.
With your images list I have this :
![image](https://user-images.githubusercontent.com/58328740/135230980-698077ca-7630-4afe-9736-3f55fcd334f6.png)
Do you accept this fix ?

**Comment by doob187** [comment]
Perfect 🥰  thx
